# Generated by Django 4.1.5 on 2023-01-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_admin_admin_password_admin_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='admin',
            name='email_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Admin_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
